api/urls.py
from django.urls import path
from rest_framework.authtoken import views as rest_view

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('all_twits/', views.all_twits, name='all_twits'),
    path('login/', views.darius_login, name='login'),
    path('logout/', views.darius_logout, name='logout'),
    path('save_pic/', views.save_pic, name='save_pic'),
    path('save_twits/', views.save_twits, name='save_twits'),
    path('user_register/', views.user_register, name='user_register'),
    path('login_page/', views.login_page, name='login_page'),
    path('v1/login/', rest_view.obtain_auth_token, name='token_login'),
    path('v1/tweet/', views.token_twits, name='api_save_twit'),
    path('v2/tweet/', views.token_generate, name='token_generator'),
    # path(r'login_page/?next=([a-zA-Z0-9/]*)', views.login_fix, name='login_fix'),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

from django.conf import settings


#Model to store the list of logged in users
class LoggedInUser(models.Model):
    user = models.OneToOneField(User, related_name='logged_in_user',on_delete=models.CASCADE)
    # Session keys are 32 characters long
    session_key = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class TwitterUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=user_directory_path, blank=True, null=True)



class Twit(models.Model):
    owner = models.ForeignKey(TwitterUser, on_delete=models.DO_NOTHING)
    date = models.DateField()
    title = models.CharField(max_length=100, default='title')
    body = models.CharField(max_length=300)


class SavedRequests(models.Model):
    ip = models.CharField(max_length=30)
    time = models.DateTimeField(auto_now=True)
    explorer = models.CharField(max_length=50)
    auth = models.BooleanField(default=True)
    def __str__(self):
        return self.ip + repr(self.time) + repr(self.explorer) + repr(self.auth)

api/forms.py
from django import forms

class UploadFileForm(forms.Form):
    avatar_pic = forms.ImageField()

api/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .models import TwitterUser, Twit, SavedRequests
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import UploadFileForm
from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authtoken.models import Token
from django.contrib.sessions.models import Session

NN=1000
HH=2


def darius_time(time1, time2, HH):
    import datetime
    time11 = datetime.datetime(time1.year, time1.month, time1.day, time1.hour, time1.minute, time1.second)
    time22 = datetime.datetime(time2.year, time2.month, time2.day, time2.hour, time2.minute, time2.second)
    timediff=time11-time22
    return timediff.total_seconds()<HH


def process_request(func):

    def wrapper(request):
        darius_auth=True
        #print(list_of_login_needing_funcs,func.__name__,func.__name__ in list_of_login_needing_funcs)
        if func.__name__ in list_of_login_needing_funcs and not request.user.is_authenticated:
            darius_auth=False
        now=SavedRequests.objects.create(explorer=request.META['HTTP_USER_AGENT'],ip=request.META['REMOTE_ADDR'],auth=darius_auth)
        now.save()

        #first and second part
        res=list((list(SavedRequests.objects.order_by('time'))))
        unautho_reqs = 0
        for i in range(len(res)):

            if res[i].ip == request.META['REMOTE_ADDR']:
                unautho_reqs +=1

            j=i+1
            reqs_sent=0

            while(j<len(res) and darius_time(res[j].time,res[i].time,HH)):
                #print(darius_time(res[j].time,res[i].time,HH))

                if res[j].ip==request.META['REMOTE_ADDR']:
                    reqs_sent+=1
                j+=1
            if reqs_sent>=NN or unautho_reqs>NN:
                return HttpResponse(status=404,reason="you are malicious")


        return func(request)
    return wrapper
@process_request
@login_required
def save_twits(request):
    twit = Twit.objects.create(owner=TwitterUser.objects.get(user=request.user), title=request.POST['twit_title'],
                               body=request.POST['twit_body'], date=timezone.now())
    twit.save()
    return redirect("/api")

@process_request
def user_register(request):
    user = User.objects.create_user(username=request.POST["user_name"],
                                    email=request.POST["user_mail"],
                                    password=request.POST["user_password"],
                                    )
    user.first_name = request.POST["visible_name"]
    user.save()
    t = TwitterUser.objects.create(user=user)
    t.save()
    return redirect("/api/login_page")

@process_request
@login_required
def all_twits(request):
    twits = reversed(list(Twit.objects.order_by('date')))
    context = {'twits': twits}
    return render(request, 'api/all_twits.html', context)

@process_request
@login_required
def save_pic(request):
    form = UploadFileForm(request.POST, request.FILES)
    if form.is_valid():
        owner = TwitterUser.objects.get(user=request.user)
        owner.avatar = request.FILES["avatar_pic"]
        owner.save()
        # MemoryFileUploadHandler(request.FILES["avatar_pic"])

    return redirect("/api")

@process_request
def darius_login(request):
    user = authenticate(request, username=request.POST["luser_name"], password=request.POST["luser_password"])
    if user is not None:

        login(request, user)
        return redirect("/api")
    else:
        return redirect("/api/login_page")

@process_request
@login_required
def index(request):
    twits = reversed(list(Twit.objects.filter(owner=TwitterUser.objects.get(user=request.user)).order_by('date')))
    context = {'twits': twits, "user": request.user, "TwitterUser": TwitterUser.objects.get(user=request.user)}
    return render(request, 'api/index.html', context)

@process_request
@login_required
def darius_logout(request):
    logout(request)
    return redirect("/api/login_page")

@process_request
def login_page(request):
    context = {}
    return render(request, 'api/login_page.html', context)

@process_request
def login_fix(request, next_page):
    return redirect("/api/login_page")


@api_view(['POST'])
@permission_classes((IsAuthenticated,))
def token_twits(request):
    user = request.user
    twit_user = TwitterUser.objects.get(user=user)
    Twit.objects.create(owner=twit_user, title=request.POST['twit_title'],
                        body=request.POST['twit_body'], date=timezone.now())
    return HttpResponse('response saved')


@login_required()
def token_generate(request):
    Token.objects.get(user=request.user).delete()
    token = Token.objects.create(user=request.user).key
    data = dict()
    data['token'] = str(token)
    return JsonResponse(data)

global list_of_login_needing_funcs
list_of_login_needing_funcs=['darius_logout','index','darius_login','save_pic','all_twits','save_twits']

templates/api/all_twits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
twits
<ul>

    {% for twit in twits %}
        <li>
            username : {{ twit.owner.user.first_name }} <br>
            body : {{ twit.title }}<br>{{ twit.body }} <br><br>
        </li>
    {% endfor %}
</ul>

</body>
</html>

templates/api/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

welcome {{ user.first_name }}
{% if TwitterUser.avatar %}
    <img height="200px" src={{ TwitterUser.avatar.url }}>
{% endif %}
<br>
<hr>
<form action='{% url 'api:save_twits' %}' method="post">
    {% csrf_token %}
    <div>
        <label for="name">new twit:</label><br>
        <input type="text" id="twit_body" name="twit_title">
    </div>
    <div>
        <label for="name">new twit:</label><br>
        <textarea id="twit_body" name="twit_body"></textarea>
    </div>

    <div>
        <button type="submit">save twit</button>
    </div>
</form>

<form action='{% url 'api:save_pic' %}' method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="name">new pic:</label><br>
        <input type="file" id="avatar_pic" name="avatar_pic">
    </div>

    <div>
        <button type="submit">save avatar</button>
    </div>
</form>

<form action="{% url 'api:token_generator' %}" method="post">
    {% csrf_token %}
    <button name="token_generate">Generate New Token</button>
</form>
<br>
twits:
<hr>
<ul>
    {% for twit in twits %}
        <li>{{ twit.title }}<br>{{ twit.body }}<br><br></li>
    {% endfor %}
</ul>

</body>
</html>

templates/api/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action={% url 'api:user_register' %} method="post">
  {% csrf_token %}
  <div>
    <label for="name">UserName:</label>
    <input type="text" id="user_name" name="user_name">
  </div>
  <div>
    <label for="name">VisibleName:</label>
    <input type="text" id="visible_name" name="visible_name">
  </div>

  <div>
    <label for="name">Password:</label>
    <input type="password" id="user_password" name="user_password">
  </div>
  <div>
    <label for="mail">E-mail:</label>
    <input type="email" id="mail" name="user_mail">
  </div>

  <div>
    <input type="submit">Submit</input>
  </div>
</form>

<form action={% url 'api:login' %} method="post">
  {% csrf_token %}
  <div>
    <label for="name">UserName:</label>
    <input type="text" id="luser_name" name="luser_name">
  </div>

  <div>
    <label for="name">Password:</label>
    <input type="password" id="luser_password" name="luser_password">
  </div>
  <div>
    <input type="submit">Submit</input>
  </div>
</form>

</body>
</html>